name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.19.x'
          cache: 'npm'
          cache-dependency-path: |
            server/package-lock.json
            frontend/package-lock.json

      - name: Install dependencies (server)
        working-directory: server
        run: npm ci

      - name: Install dependencies (frontend)
        working-directory: frontend
        run: npm ci

      - name: Run tests (server)
        working-directory: server
        run: npm test

      - name: Run tests (frontend)
        working-directory: frontend
        run: npm test

      - name: Build frontend
        working-directory: frontend
        run: npm run build

      - name: Install Playwright browsers
        working-directory: frontend
        run: npx playwright install --with-deps

      - name: Run Playwright end-to-end tests
        working-directory: frontend
        env:
          PLAYWRIGHT_HTML_REPORT: playwright-report
        run: npm run test:e2e

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: frontend/playwright-report
          if-no-files-found: warn
